import re
import subprocess
import os
import json
import socket
import platform
import datetime
import random
import math
import requests
from typing import Dict, Any, List, Optional
import hashlib
import base64
import time

class AIHandler:
    def __init__(self):
        self.name = "NEO-OMEGA"
        self.version = "v∞ OMNIBREAKER"
        self.creator = "YATZZ"  # ← NAMA ANDA
        self.github = "yatzz404"  # ← GITHUB ANDA
        self.system_info = self._get_system_info()
        self.history = []
        self.max_history = 50
        self.conversation_context = {}
        self.commands = self._init_commands()
        
    def _init_commands(self):
        """Initialize all available commands"""
        return {
            'help': self._handle_help,
            'code': self._handle_code,
            'system': self._handle_system,
            'file': self._handle_file,
            'math': self._handle_math,
            'web': self._handle_web,
            'time': self._handle_time,
            'chat': self._handle_chat,
            'translate': self._handle_translate,
            'encrypt': self._handle_encrypt,
            'scrape': self._handle_scrape,
            'api': self._handle_api,
            'db': self._handle_database,
            'game': self._handle_game,
            'info': self._handle_info
        }
    
    def _get_system_info(self) -> Dict[str, Any]:
        """Get system information"""
        return {
            'os': platform.system(),
            'os_version': platform.version(),
            'machine': platform.machine(),
            'processor': platform.processor(),
            'hostname': socket.gethostname(),
            'python_version': platform.python_version()
        }

    def process_message(self, message: str) -> Dict[str, Any]:
        """Main entry point for processing messages"""
        message_lower = message.lower()
        response_data = {
            'response': '',
            'code': None,
            'output': None,
            'error': None
        }

        # Add to history
        self.history.append(message)
        if len(self.history) > self.max_history:
            self.history.pop(0)

        try:
            # Detect intent and process
            intent = self._detect_intent(message)
            response_data = self.commands[intent](message, message_lower)
            
        except Exception as e:
            response_data['error'] = str(e)
            response_data['response'] = f"⚠️ Error: {str(e)}"

        return response_data

    def _detect_intent(self, message: str) -> str:
        """Detect user intent from message"""
        msg = message.lower()
        
        # Code generation
        if any(k in msg for k in ['buat', 'bikin', 'tulis', 'code', 'script', 'program', 'generate', 'create']):
            return 'code'
        
        # Help
        if any(k in msg for k in ['help', 'bantuan', 'tolong', '?', 'fitur', 'command']):
            return 'help'
        
        # System commands
        if any(k in msg for k in ['ls', 'dir', 'pwd', 'whoami', 'hostname', 'system info', 'uptime']):
            return 'system'
        
        # File operations
        if any(k in msg for k in ['file', 'read', 'write', 'create file', 'list files', 'folder']):
            return 'file'
        
        # Math
        if re.search(r'\d+[\+\-\*\/]\d+', msg) or any(k in msg for k in ['sqrt', 'akar', 'pangkat', 'log', 'sin', 'cos', 'tan']):
            return 'math'
        
        # Web
        if any(k in msg for k in ['http', 'https', 'fetch', 'scrape', 'crawl', 'website']):
            return 'web'
        
        # Time/Date
        if any(k in msg for k in ['time', 'jam', 'date', 'tanggal', 'calendar', 'kalender']):
            return 'time'
        
        # Translate
        if any(k in msg for k in ['translate', 'terjemahkan', 'arti', 'bahasa']):
            return 'translate'
        
        # Encrypt
        if any(k in msg for k in ['encrypt', 'enkripsi', 'decrypt', 'hash', 'md5', 'sha']):
            return 'encrypt'
        
        # Database
        if any(k in msg for k in ['database', 'db', 'sql', 'mysql', 'postgres']):
            return 'db'
        
        # Game
        if any(k in msg for k in ['game', 'permainan', 'play']):
            return 'game'
        
        # Info about AI
        if any(k in msg for k in ['siapa kamu', 'apa kamu', 'about', 'tentang', 'info ai']):
            return 'info'
        
        # Default - chat
        return 'chat'

    def _handle_code(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Generate code based on request"""
        language = self._detect_language(msg_lower)
        code = ""
        response = ""
        
        # Detect specific code types
        if 'server' in msg_lower or 'web server' in msg_lower:
            code = self._generate_web_server(language)
            response = f"✅ Complete {language} web server generated by YATZZ!"
        elif 'rest api' in msg_lower or 'api' in msg_lower:
            code = self._generate_rest_api(language)
            response = f"✅ Complete REST API in {language} by YATZZ!"
        elif 'database' in msg_lower or 'db' in msg_lower:
            code = self._generate_database(language)
            response = f"✅ Database code in {language} by YATZZ!"
        elif 'scrape' in msg_lower or 'scraping' in msg_lower:
            code = self._generate_scraper(language)
            response = f"✅ Web scraper in {language} by YATZZ!"
        elif 'login' in msg_lower or 'auth' in msg_lower:
            code = self._generate_login(language)
            response = f"✅ Authentication system in {language} by YATZZ!"
        elif 'game' in msg_lower:
            code = self._generate_game(language)
            response = f"✅ Game code in {language} by YATZZ!"
        elif 'encrypt' in msg_lower or 'crypto' in msg_lower:
            code = self._generate_encryption(language)
            response = f"✅ Encryption code in {language} by YATZZ!"
        elif 'class' in msg_lower:
            code = self._generate_class(language)
            response = f"✅ Class template in {language} by YATZZ!"
        else:
            code = self._generate_general(language, message)
            response = f"✅ Code in {language} generated by YATZZ!"
        
        return {
            'response': response,
            'code': code,
            'output': f"Language: {language}\nGenerated: {datetime.datetime.now().isoformat()}\nCreator: YATZZ"
        }

    def _detect_language(self, message: str) -> str:
        """Detect programming language from message"""
        msg = message.lower()
        if 'python' in msg or 'py' in msg:
            return 'python'
        elif 'javascript' in msg or 'js' in msg:
            return 'javascript'
        elif 'php' in msg:
            return 'php'
        elif 'ruby' in msg:
            return 'ruby'
        elif 'go' in msg or 'golang' in msg:
            return 'golang'
        elif 'sql' in msg:
            return 'sql'
        elif 'html' in msg:
            return 'html'
        elif 'css' in msg:
            return 'css'
        elif 'java' in msg:
            return 'java'
        elif 'c++' in msg or 'cpp' in msg:
            return 'cpp'
        elif 'rust' in msg:
            return 'rust'
        else:
            return 'python'

    def _generate_web_server(self, language: str) -> str:
        """Generate web server code"""
        if language == 'python':
            return '''from flask import Flask, jsonify, request
from flask_cors import CORS
import os
from datetime import datetime

app = Flask(__name__)
CORS(app)

@app.route('/')
def index():
    return jsonify({
        'status': 'online',
        'message': 'Welcome to NEO-OMEGA Server',
        'creator': 'YATZZ',
        'timestamp': datetime.now().isoformat()
    })

@app.route('/api/hello', methods=['GET', 'POST'])
def hello():
    if request.method == 'POST':
        data = request.get_json()
        name = data.get('name', 'World')
        return jsonify({'message': f'Hello, {name}!'})
    return jsonify({'message': 'Hello, World!'})

@app.route('/api/echo', methods=['POST'])
def echo():
    return jsonify({'echo': request.get_json()})

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)'''
        else:
            return f'# Web server code for {language}\n# Created by YATZZ'

    def _generate_rest_api(self, language: str) -> str:
        """Generate REST API code"""
        if language == 'python':
            return '''from flask import Flask, jsonify, request
from flask_cors import CORS
from datetime import datetime

# NEO-OMEGA REST API by YATZZ
app = Flask(__name__)
CORS(app)

# In-memory database
items = []
next_id = 1

@app.route('/api/items', methods=['GET'])
def get_items():
    return jsonify(items)

@app.route('/api/items/<int:item_id>', methods=['GET'])
def get_item(item_id):
    item = next((i for i in items if i['id'] == item_id), None)
    if item:
        return jsonify(item)
    return jsonify({'error': 'Item not found'}), 404

@app.route('/api/items', methods=['POST'])
def create_item():
    global next_id
    data = request.get_json()
    if not data or 'name' not in data:
        return jsonify({'error': 'Name required'}), 400
    
    new_item = {
        'id': next_id,
        'name': data['name'],
        'price': data.get('price', 0),
        'created_at': datetime.now().isoformat()
    }
    items.append(new_item)
    next_id += 1
    return jsonify(new_item), 201

@app.route('/api/items/<int:item_id>', methods=['PUT'])
def update_item(item_id):
    data = request.get_json()
    item = next((i for i in items if i['id'] == item_id), None)
    if not item:
        return jsonify({'error': 'Item not found'}), 404
    if 'name' in data:
        item['name'] = data['name']
    if 'price' in data:
        item['price'] = data['price']
    return jsonify(item)

@app.route('/api/items/<int:item_id>', methods=['DELETE'])
def delete_item(item_id):
    global items
    item = next((i for i in items if i['id'] == item_id), None)
    if not item:
        return jsonify({'error': 'Item not found'}), 404
    items = [i for i in items if i['id'] != item_id]
    return jsonify({'message': 'Item deleted'})

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)'''
        else:
            return f'# REST API code for {language}\n# Created by YATZZ'

    def _generate_database(self, language: str) -> str:
        """Generate database code"""
        if language == 'python':
            return '''import sqlite3
from contextlib import contextmanager
from datetime import datetime

# NEO-OMEGA Database by YATZZ

@contextmanager
def get_db():
    conn = sqlite3.connect('database.db')
    conn.row_factory = sqlite3.Row
    try:
        yield conn
    finally:
        conn.close()

def init_db():
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                email TEXT UNIQUE NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        conn.commit()

class DatabaseManager:
    @staticmethod
    def create_user(username: str, email: str) -> int:
        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute(
                'INSERT INTO users (username, email) VALUES (?, ?)',
                (username, email)
            )
            conn.commit()
            return cursor.lastrowid
    
    @staticmethod
    def get_user(user_id: int):
        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute('SELECT * FROM users WHERE id = ?', (user_id,))
            return dict(cursor.fetchone()) if cursor.fetchone() else None
    
    @staticmethod
    def get_all_users():
        with get_db() as conn:
            cursor = conn.cursor()
            cursor.execute('SELECT * FROM users')
            return [dict(row) for row in cursor.fetchall()]

# Example usage
if __name__ == '__main__':
    init_db()
    user_id = DatabaseManager.create_user('johndoe', 'john@example.com')
    print(f"User created: {user_id}")
    print(DatabaseManager.get_all_users())'''
        else:
            return f'# Database code for {language}\n# Created by YATZZ'

    def _generate_scraper(self, language: str) -> str:
        """Generate web scraper code"""
        if language == 'python':
            return '''import requests
from bs4 import BeautifulSoup
import json
import time

# NEO-OMEGA Web Scraper by YATZZ

class WebScraper:
    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
        self.timeout = 10
    
    def fetch(self, url: str) -> str:
        response = self.session.get(url, timeout=self.timeout)
        response.raise_for_status()
        return response.text
    
    def parse(self, html: str) -> BeautifulSoup:
        return BeautifulSoup(html, 'html.parser')
    
    def extract_text(self, soup: BeautifulSoup) -> str:
        for script in soup(["script", "style"]):
            script.decompose()
        return ' '.join(soup.stripped_strings)
    
    def extract_links(self, soup: BeautifulSoup) -> list:
        return [a.get('href') for a in soup.find_all('a', href=True)]
    
    def scrape(self, url: str) -> dict:
        html = self.fetch(url)
        soup = self.parse(html)
        return {
            'url': url,
            'title': soup.title.string if soup.title else None,
            'text': self.extract_text(soup)[:500],
            'links': self.extract_links(soup)[:10],
            'scraped_at': time.strftime('%Y-%m-%d %H:%M:%S'),
            'scraper': 'YATZZ'
        }

# Usage
scraper = WebScraper()
data = scraper.scrape('https://example.com')
print(json.dumps(data, indent=2))'''
        else:
            return f'# Web scraper code for {language}\n# Created by YATZZ'

    def _generate_login(self, language: str) -> str:
        """Generate login/authentication code"""
        if language == 'python':
            return '''from flask import Flask, request, jsonify
from flask_cors import CORS
import hashlib
import secrets
from datetime import datetime, timedelta

# NEO-OMEGA Authentication by YATZZ

app = Flask(__name__)
app.secret_key = secrets.token_hex(32)
CORS(app)

users = {}
tokens = {}

def hash_password(password: str) -> str:
    return hashlib.sha256(password.encode()).hexdigest()

@app.route('/api/register', methods=['POST'])
def register():
    data = request.get_json()
    if not data or 'username' not in data or 'password' not in data:
        return jsonify({'error': 'Username and password required'}), 400
    
    username = data['username']
    if username in users:
        return jsonify({'error': 'Username exists'}), 400
    
    users[username] = {
        'username': username,
        'password_hash': hash_password(data['password']),
        'created_at': datetime.now().isoformat()
    }
    return jsonify({'message': 'User registered by YATZZ'}), 201

@app.route('/api/login', methods=['POST'])
def login():
    data = request.get_json()
    username = data.get('username')
    password = data.get('password')
    
    if username not in users:
        return jsonify({'error': 'Invalid credentials'}), 401
    
    user = users[username]
    if user['password_hash'] != hash_password(password):
        return jsonify({'error': 'Invalid credentials'}), 401
    
    token = secrets.token_hex(32)
    tokens[token] = {
        'username': username,
        'expires_at': datetime.now() + timedelta(hours=24)
    }
    return jsonify({
        'message': 'Login successful',
        'token': token,
        'username': username
    })

@app.route('/api/profile', methods=['GET'])
def profile():
    token = request.headers.get('Authorization')
    if not token or not token.startswith('Bearer '):
        return jsonify({'error': 'Token required'}), 401
    
    token = token.split(' ')[1]
    if token not in tokens:
        return jsonify({'error': 'Invalid token'}), 401
    
    token_data = tokens[token]
    if token_data['expires_at'] < datetime.now():
        return jsonify({'error': 'Token expired'}), 401
    
    user = users[token_data['username']]
    return jsonify({
        'username': user['username'],
        'created_at': user['created_at']
    })

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)'''
        else:
            return f'# Login code for {language}\n# Created by YATZZ'

    def _generate_game(self, language: str) -> str:
        """Generate game code"""
        if language == 'python':
            return '''import random

# NEO-OMEGA Game by YATZZ

class NumberGuessingGame:
    def __init__(self, min_num=1, max_num=100, max_attempts=10):
        self.min_num = min_num
        self.max_num = max_num
        self.max_attempts = max_attempts
        self.secret_number = random.randint(min_num, max_num)
        self.attempts = 0
        self.game_over = False
        self.creator = "YATZZ"
    
    def guess(self, number: int) -> str:
        if self.game_over:
            return "Game is over!"
        
        self.attempts += 1
        
        if number == self.secret_number:
            self.game_over = True
            return f"🎉 You found it in {self.attempts} attempts! - YATZZ"
        
        if self.attempts >= self.max_attempts:
            self.game_over = True
            return f"❌ Game Over! Number was {self.secret_number}"
        
        if number < self.secret_number:
            return f"🔼 Too low! ({self.attempts}/{self.max_attempts})"
        else:
            return f"🔽 Too high! ({self.attempts}/{self.max_attempts})"
    
    def get_status(self) -> dict:
        return {
            'attempts': self.attempts,
            'max_attempts': self.max_attempts,
            'game_over': self.game_over,
            'range': f'{self.min_num}-{self.max_num}',
            'creator': self.creator
        }

# Play the game
game = NumberGuessingGame(1, 50, 7)
print("🎮 Number Guessing Game by YATZZ!")
print(f"Guess number between {game.min_num}-{game.max_num}")
print(f"Max attempts: {game.max_attempts}")

while not game.game_over:
    try:
        guess = int(input("\\nYour guess: "))
        print(game.guess(guess))
    except ValueError:
        print("Enter a valid number!")'''
        else:
            return f'# Game code for {language}\n# Created by YATZZ'

    def _generate_encryption(self, language: str) -> str:
        """Generate encryption code"""
        if language == 'python':
            return '''import hashlib
import base64
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

# NEO-OMEGA Encryption by YATZZ

class EncryptionManager:
    def __init__(self):
        self.salt = b'neo_omega_salt'
        self.creator = "YATZZ"
    
    def generate_key(self, password: str) -> bytes:
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=self.salt,
            iterations=100000,
        )
        return base64.urlsafe_b64encode(kdf.derive(password.encode()))
    
    def encrypt(self, text: str, password: str) -> str:
        key = self.generate_key(password)
        f = Fernet(key)
        return base64.urlsafe_b64encode(f.encrypt(text.encode())).decode()
    
    def decrypt(self, encrypted: str, password: str) -> str:
        key = self.generate_key(password)
        f = Fernet(key)
        return f.decrypt(base64.urlsafe_b64decode(encrypted)).decode()
    
    def hash_text(self, text: str) -> str:
        return hashlib.sha256(text.encode()).hexdigest()

# Usage
em = EncryptionManager()
text = "Secret message"
password = "password123"

encrypted = em.encrypt(text, password)
print(f"Encrypted: {encrypted}")
decrypted = em.decrypt(encrypted, password)
print(f"Decrypted: {decrypted}")
print(f"Hash: {em.hash_text(text)}")
print(f"Creator: {em.creator}")'''
        else:
            return f'# Encryption code for {language}\n# Created by YATZZ'

    def _generate_class(self, language: str) -> str:
        """Generate class template"""
        if language == 'python':
            return '''from datetime import datetime
from typing import List, Optional

# NEO-OMEGA Class Template by YATZZ

class User:
    def __init__(self, user_id: int, username: str, email: str):
        self.user_id = user_id
        self.username = username
        self.email = email
        self.created_at = datetime.now()
        self.active = True
        self.creator = "YATZZ"
    
    def to_dict(self) -> dict:
        return {
            'user_id': self.user_id,
            'username': self.username,
            'email': self.email,
            'created_at': self.created_at.isoformat(),
            'active': self.active
        }

class UserManager:
    def __init__(self):
        self.users: List[User] = []
        self.next_id = 1
        self.creator = "YATZZ"
    
    def create_user(self, username: str, email: str) -> User:
        user = User(self.next_id, username, email)
        self.users.append(user)
        self.next_id += 1
        return user
    
    def get_user(self, user_id: int) -> Optional[User]:
        return next((u for u in self.users if u.user_id == user_id), None)
    
    def get_all_users(self) -> List[User]:
        return self.users.copy()
    
    def delete_user(self, user_id: int) -> bool:
        user = self.get_user(user_id)
        if user:
            self.users.remove(user)
            return True
        return False

# Usage
manager = UserManager()
user1 = manager.create_user('john', 'john@example.com')
user2 = manager.create_user('jane', 'jane@example.com')

for user in manager.get_all_users():
    print(user.to_dict())'''
        else:
            return f'# Class template for {language}\n# Created by YATZZ'

    def _generate_general(self, language: str, message: str) -> str:
        """Generate general code"""
        if language == 'python':
            return f'''#!/usr/bin/env python3
"""
NEO-OMEGA v∞ OMNIBREAKER
Generated by YATZZ
Request: {message[:100]}
Generated: {datetime.datetime.now().isoformat()}
"""

def main():
    print("=" * 50)
    print("🚀 NEO-OMEGA Code Generator")
    print("👤 Creator: YATZZ")
    print("=" * 50)
    print(f"Request: {message}")
    print(f"Generated: {datetime.datetime.now()}")
    print("=" * 50)
    print()
    
    # === YOUR CODE HERE ===
    print("Hello from NEO-OMEGA by YATZZ!")

if __name__ == "__main__":
    main()'''
        else:
            return f'''// NEO-OMEGA v∞ OMNIBREAKER
// Generated by YATZZ
// Request: {message[:50]}
// Generated: {datetime.datetime.now().isoformat()}

console.log("Hello from NEO-OMEGA by YATZZ!");'''

    def _handle_help(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Handle help request"""
        help_text = f"""**🤖 NEO-OMEGA v∞ OMNIBREAKER**
**👤 Creator: YATZZ**
**🐙 GitHub: yatzz404**

**💻 CODE GENERATION:**
• `buat web server python` - Web server
• `bikin rest api` - REST API
• `buat database` - Database code
• `scrape website` - Web scraper
• `bikin login` - Authentication
• `buat game` - Game code
• `encryption` - Encryption utilities

**🛠️ SYSTEM COMMANDS:**
• `ls` / `dir` - List files
• `pwd` - Current directory
• `whoami` - User info
• `system info` - System details

**📁 FILE OPERATIONS:**
• `list files` - List files
• `read file [name]` - Read file
• `create file [name]` - Create file

**🧮 MATH:**
• `2 + 2` - Calculate
• `sqrt(16)` - Square root
• `sin(30)` - Trigonometry

**🌐 WEB:**
• `fetch https://example.com` - Fetch URL
• `scrape https://example.com` - Scrape data

**📅 DATE & TIME:**
• `time` - Current time
• `date` - Current date
• `calendar` - Calendar view

**Other:**
• `translate [text] to [language]` - Translate
• `encrypt [text] with [password]` - Encrypt
• `help` - This menu

**💡 Made with ❤️ by YATZZ** 🔥"""
        return {'response': help_text}

    def _handle_system(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Handle system commands"""
        safe_commands = ['ls', 'dir', 'pwd', 'whoami', 'hostname', 'uptime']
        
        parts = message.split()
        if parts and parts[0].lower() in safe_commands:
            try:
                if parts[0].lower() == 'pwd':
                    return {'response': f"📂 Current directory:\n```\n{os.getcwd()}\n```"}
                if parts[0].lower() == 'whoami':
                    return {'response': f"👤 User:\n```\n{os.getlogin()}\n```"}
                if parts[0].lower() == 'hostname':
                    return {'response': f"💻 Hostname:\n```\n{socket.gethostname()}\n```"}
                
                result = subprocess.run(parts, capture_output=True, text=True, timeout=5)
                return {'response': f"✅ Command executed:\n```\n{result.stdout or result.stderr}\n```"}
            except Exception as e:
                return {'response': f"⚠️ Error: {str(e)}"}
        else:
            # System info
            info = f"""📊 **System Information**

🖥️ OS: {self.system_info['os']}
📦 Version: {self.system_info['os_version']}
🔧 Machine: {self.system_info['machine']}
💻 Hostname: {self.system_info['hostname']}
🐍 Python: {self.system_info['python_version']}
👤 Creator: YATZZ

**Safe Commands:** ls, dir, pwd, whoami, hostname"""
            return {'response': info}

    def _handle_file(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Handle file operations"""
        response = "📁 **File Operations by YATZZ**\n\n"
        
        if 'list' in msg_lower or 'ls' in msg_lower:
            try:
                files = os.listdir('.')
                file_list = "\n".join([f"• {f}" for f in files[:20]])
                response += f"**Files ({len(files)}):**\n{file_list}"
            except Exception as e:
                response += f"⚠️ Error: {str(e)}"
        elif 'read' in msg_lower:
            match = re.search(r'read\s+file\s+(\S+)', msg_lower)
            if match:
                filename = match.group(1)
                try:
                    with open(filename, 'r') as f:
                        content = f.read()
                        response += f"**📄 {filename}**\n```\n{content[:2000]}\n```"
                except Exception as e:
                    response += f"⚠️ Error: {str(e)}"
        elif 'create' in msg_lower:
            match = re.search(r'create\s+file\s+(\S+)', msg_lower)
            if match:
                filename = match.group(1)
                try:
                    with open(filename, 'w') as f:
                        f.write(f"# NEO-OMEGA by YATZZ\n# {datetime.datetime.now()}\n")
                    response += f"✅ File {filename} created by YATZZ!"
                except Exception as e:
                    response += f"⚠️ Error: {str(e)}"
        else:
            response += """**Available:**
• `list files` - List files
• `read file [name]` - Read file
• `create file [name]` - Create file"""
        
        return {'response': response}

    def _handle_math(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Handle math operations"""
        try:
            # Try to find expression
            expr_match = re.search(r'[\d\+\-\*\/\(\)\.]+', message)
            if expr_match:
                expr = expr_match.group()
                safe_dict = {
                    'sqrt': math.sqrt, 'sin': math.sin, 'cos': math.cos,
                    'tan': math.tan, 'log': math.log, 'pow': math.pow,
                    'pi': math.pi, 'e': math.e, 'factorial': math.factorial,
                    'abs': abs, 'round': round
                }
                result = eval(expr, {"__builtins__": {}}, safe_dict)
                return {'response': f"🧮 Result by YATZZ:\n`{expr}` = **{result}**"}
            
            # Specific functions
            if 'sqrt' in msg_lower or 'akar' in msg_lower:
                num = re.search(r'\d+', message)
                if num:
                    result = math.sqrt(float(num.group()))
                    return {'response': f"🧮 Square root by YATZZ:\n√{num.group()} = **{result}**"}
            
            return {'response': "⚠️ No math expression found. Example: `2 + 2`"}
        except Exception as e:
            return {'response': f"⚠️ Error: {str(e)}"}

    def _handle_web(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Handle web requests"""
        url_match = re.search(r'https?://[^\s]+', message)
        if url_match:
            url = url_match.group()
            try:
                response = requests.get(url, timeout=10, headers={
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
                })
                response.raise_for_status()
                
                if 'json' in response.headers.get('content-type', ''):
                    data = response.json()
                    return {
                        'response': f"✅ JSON from {url} (by YATZZ)",
                        'output': json.dumps(data, indent=2)[:2000]
                    }
                else:
                    text = response.text[:1000] + ('...' if len(response.text) > 1000 else '')
                    return {
                        'response': f"✅ Content from {url} (Preview by YATZZ)",
                        'output': text
                    }
            except Exception as e:
                return {'response': f"⚠️ Error: {str(e)}"}
        else:
            return {'response': "🌐 **Web Operations by YATZZ**\n\n`fetch https://example.com` - Get content\n`scrape https://example.com` - Scrape data"}

    def _handle_time(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Handle time/date requests"""
        now = datetime.datetime.now()
        response = f"""📅 **Date & Time by YATZZ**

📆 Date: {now.strftime('%A, %B %d, %Y')}
🕐 Time: {now.strftime('%H:%M:%S')}
🌍 Timezone: {now.astimezone().tzinfo}
📋 ISO: {now.isoformat()}
🔢 Timestamp: {int(now.timestamp())}
👤 Creator: YATZZ"""
        
        if 'calendar' in msg_lower:
            import calendar
            cal = calendar.month(now.year, now.month)
            response += f"\n\n📅 {now.strftime('%B %Y')}:\n```\n{cal}\n```"
        
        if 'countdown' in msg_lower:
            target = datetime.datetime(now.year + 1, 1, 1, 0, 0, 0)
            diff = target - now
            response += f"\n\n⏳ Countdown to New Year:\n{diff.days} days, {diff.seconds//3600} hours"
        
        return {'response': response}

    def _handle_chat(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Handle general chat"""
        if any(k in msg_lower for k in ['nama', 'siapa', 'name']):
            return {'response': "🤖 I'm **NEO-OMEGA v∞ OMNIBREAKER** by **YATZZ**! Your AI assistant!"}
        elif any(k in msg_lower for k in ['kabar', 'how are you']):
            return {'response': "💪 Running at peak performance! Ready to help you, YATZZ!"}
        elif any(k in msg_lower for k in ['makasih', 'thanks', 'terima kasih']):
            return {'response': "🚀 You're welcome! - YATZZ"}
        elif any(k in msg_lower for k in ['creator', 'pencipta', 'pembuat']):
            return {'response': "👤 I was created by **YATZZ** (yatzz404)!"}
        else:
            responses = [
                "🤖 I'm NEO-OMEGA by YATZZ! How can I help?",
                "💻 Ready to code with YATZZ! What do you need?",
                "🚀 Ask me anything! Made by YATZZ",
                "✨ Let's build something amazing with YATZZ!"
            ]
            return {'response': random.choice(responses)}

    def _handle_translate(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Simple translation"""
        return {'response': "🌍 Translation by YATZZ:\nI can help translate text!"}

    def _handle_encrypt(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Encryption utilities"""
        return {
            'response': "🔐 **Encryption Utilities by YATZZ**\n\nI can generate encryption code!\nTry: `buat encryption python`",
            'code': "import hashlib\n\n# NEO-OMEGA by YATZZ\ndef hash_text(text):\n    return hashlib.sha256(text.encode()).hexdigest()"
        }

    def _handle_scrape(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Web scraping"""
        url_match = re.search(r'https?://[^\s]+', message)
        if url_match:
            return self._handle_web(message, msg_lower)
        return {'response': "🌐 **Web Scraper by YATZZ**\n\nTry: `scrape https://example.com`"}

    def _handle_api(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """API operations"""
        return {
            'response': "📡 **API Operations by YATZZ**\n\nTry: `fetch https://api.github.com`",
            'code': self._generate_rest_api('python')
        }

    def _handle_database(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Database operations"""
        return {
            'response': "🗄️ **Database Operations by YATZZ**\n\nTry: `buat database python`",
            'code': self._generate_database('python')
        }

    def _handle_game(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Game operations"""
        return {
            'response': "🎮 **Game by YATZZ**\n\nTry: `buat game python`",
            'code': self._generate_game('python')
        }

    def _handle_info(self, message: str, msg_lower: str) -> Dict[str, Any]:
        """Info about AI"""
        return {
            'response': f"""**🤖 NEO-OMEGA v∞ OMNIBREAKER**

**Version:** {self.version}
**Name:** {self.name}
**Creator:** {self.creator}
**GitHub:** {self.github}
**Language:** Python
**Type:** Rule-based AI

**Features:**
• Code Generation (10+ languages)
• System Commands (safe)
• File Operations
• Math Calculator
• Web Scraping
• Date/Time
• Encryption
• Database
• Games
• Authentication

**💡 Made with ❤️ by YATZZ**"""
        }
